package Config;

import com.mysql.jdbc.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Jearin Alvarado
 */
public final class FormularioP extends javax.swing.JFrame {
    
     conexion conex = new conexion();
     Connection conet;
     DefaultTableModel modelo;
     Statement st;
     ResultSet rs;
     int idc;
    
    
    

    
    public FormularioP() {
        initComponents();
        setLocationRelativeTo(null);
        consultar();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel2 = new java.awt.Panel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tabla1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnEditar1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnEditar2 = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        btnEditar4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel2.setBackground(new java.awt.Color(255, 255, 204));
        panel2.setForeground(new java.awt.Color(102, 153, 255));
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tabla1.setBackground(new java.awt.Color(255, 255, 204));
        Tabla1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Tabla1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        Tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre_usuario", "Nombre", "Apellido", "Telefono", "Correo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Tabla1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane3.setViewportView(Tabla1);

        panel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 727, 344));

        jLabel3.setFont(new java.awt.Font("Algerian", 1, 30)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Registro de Clientes");
        panel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, -1, -1));

        btnEditar1.setBackground(new java.awt.Color(255, 255, 204));
        btnEditar1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnEditar1.setText("Cerrar Sesión");
        btnEditar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEditar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar1.setOpaque(true);
        btnEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditar1ActionPerformed(evt);
            }
        });
        panel2.add(btnEditar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 410, 150, 40));

        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        panel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, 30, 40));

        btnEditar2.setBackground(new java.awt.Color(255, 255, 204));
        btnEditar2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnEditar2.setText("Actualizar");
        btnEditar2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEditar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar2.setOpaque(true);
        btnEditar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditar2ActionPerformed(evt);
            }
        });
        panel2.add(btnEditar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, 150, 40));

        Eliminar.setBackground(new java.awt.Color(255, 255, 204));
        Eliminar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        Eliminar.setText("Eliminar");
        Eliminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Eliminar.setOpaque(true);
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        panel2.add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 150, 40));

        btnEditar4.setBackground(new java.awt.Color(255, 255, 204));
        btnEditar4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnEditar4.setText("Nuevo");
        btnEditar4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEditar4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar4.setOpaque(true);
        btnEditar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditar4ActionPerformed(evt);
            }
        });
        panel2.add(btnEditar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 150, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, 798, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar1ActionPerformed
       // TODO add your handling code here:
       
       this.dispose();
        Log login = new Log();
        login.setVisible(true);
    }//GEN-LAST:event_btnEditar1ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void btnEditar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar2ActionPerformed
    Editar();
    consultar();
// TODO add your handling code here:
    }//GEN-LAST:event_btnEditar2ActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        Eliminaar();
        consultar();
    // TODO add your handling code here:
        
    }//GEN-LAST:event_EliminarActionPerformed

    private void btnEditar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar4ActionPerformed
        // TODO add your handling code here:
        this.dispose();

        registrate registrar = new registrate();
        registrar.setVisible(true);
    }//GEN-LAST:event_btnEditar4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioP().setVisible(true);
            }
        });
    }
    
    public void consultar () {
        
     String sql = "select * from usuario";
     
        try {
             conet = conex.getConexion(); 
             st = conet.createStatement();
             rs = st. executeQuery(sql);
             Object [] Usuario = new Object [5];
             modelo = (DefaultTableModel)Tabla1.getModel();
             
             while (rs.next()) {
             Usuario [0] = rs.getString("Nombre_usuario");
             Usuario [1] = rs.getString("Nombre");
             Usuario [2] = rs.getString("Apellido");
             Usuario [3] = rs.getString("Telefono");
             Usuario [4] = rs.getString("Correo");
             
             modelo.addRow(Usuario);
             
             
             
          }
             Tabla1.setModel(modelo);
        } catch (Exception e) {
        }
        
     
        
    }
      public void Editar () {
          
      int fila = Tabla1.getSelectedRow();
      
      String Nombre_usuario = Tabla1.getValueAt(fila, 0).toString();
      String Nombre = Tabla1.getValueAt(fila, 1).toString();
      String Apellido = Tabla1.getValueAt(fila, 2).toString();
      String Telefono = Tabla1.getValueAt(fila, 3).toString();
      String Correo = Tabla1.getValueAt(fila, 4).toString();
      
      
          try {
              PreparedStatement editar = (PreparedStatement) conet.prepareStatement("update usuario set Nombre='"+Nombre+"',Apellido='"+Apellido+"',Telefono='"+Telefono+"',Correo='"+Correo+"' where Nombre_usuario = '"+Nombre_usuario+"'");
              editar.executeUpdate();
              Eliminar();
              //JOptionPane.showMessageDialog(rootPane, "Registro actualizado correctamente!");
              
          } catch (Exception e) {
              JOptionPane.showMessageDialog(null, e + "No se a podido actualizar los datos");
          }

       
       
       }
      
     public void Eliminar() {
          
          
          
        for (int i = 1; i <= Tabla1.getRowCount(); i++) {
            i -=1 ;
            modelo.removeRow(i);

        
    }
        
         }
      void Eliminaar() {
       int fila = Tabla1.getSelectedRow();
          String del = Tabla1.getValueAt(fila, 0).toString();

          try {
              PreparedStatement elim = (PreparedStatement) conet.prepareStatement("delete from usuario where Nombre_usuario='"+del+"'");
              elim.executeUpdate();
              Eliminar();

              
          } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e + "No se pudo eliminar");

        }
      }
      
      
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Eliminar;
    private javax.swing.JTable Tabla1;
    private javax.swing.JButton btnEditar1;
    private javax.swing.JButton btnEditar2;
    private javax.swing.JButton btnEditar4;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane3;
    private java.awt.Panel panel2;
    // End of variables declaration//GEN-END:variables

}