
package Config;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Jearin Alvarado
 */
public class registrate extends javax.swing.JFrame {

    /**
     * Creates new form registrate
     */
    public registrate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        txtfuera = new LIB.JTexfieldPH_FielTex();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Password = new LIB.JTexfieldPH_Password();
        jPanel4 = new javax.swing.JPanel();
        user3 = new LIB.JTexfieldPH_FielTex();
        jPanel5 = new javax.swing.JPanel();
        user2 = new LIB.JTexfieldPH_FielTex();
        jPanel6 = new javax.swing.JPanel();
        user4 = new LIB.JTexfieldPH_FielTex();
        jPanel8 = new javax.swing.JPanel();
        Password2 = new LIB.JTexfieldPH_Password();
        jPanel7 = new javax.swing.JPanel();
        user5 = new LIB.JTexfieldPH_FielTex();
        jPanel9 = new javax.swing.JPanel();
        user6 = new LIB.JTexfieldPH_FielTex();

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txtfuera.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtfuera.setPlaceholder("NombreUsuario");
        jPanel3.add(txtfuera);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 30)); // NOI18N
        jLabel1.setText("Crear cuenta ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 280, 40));

        btnIniciar.setBackground(new java.awt.Color(255, 204, 204));
        btnIniciar.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnIniciar.setText("Inicia sesion");
        btnIniciar.setActionCommand("Inicia sesion");
        btnIniciar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnIniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIniciar.setOpaque(true);
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 230, 40));

        btnCrear.setBackground(new java.awt.Color(255, 204, 204));
        btnCrear.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnCrear.setText("Añadir Cuenta");
        btnCrear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrear.setOpaque(true);
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 230, 40));

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jLabel10.setText("Ya te habias registrado?");
        jLabel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, -1, -1));

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        Password.setName("Password"); // NOI18N
        Password.setOpaque(true);
        Password.setPlaceholder("Contraseña");
        jPanel2.add(Password);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 210, -1));

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        user3.setPlaceholder("Apellido");
        jPanel4.add(user3);

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 210, 50));

        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        user2.setPlaceholder("Nombre");
        user2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user2ActionPerformed(evt);
            }
        });
        jPanel5.add(user2);

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 210, 50));

        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        user4.setPlaceholder("Telefono");
        jPanel6.add(user4);

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 210, 50));

        jPanel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        Password2.setOpaque(true);
        Password2.setPlaceholder("ConfirmarContraseña");
        jPanel8.add(Password2);

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 210, -1));

        jPanel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        user5.setPlaceholder("@Gmail");
        jPanel7.add(user5);

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 210, -1));

        jPanel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel9.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        user6.setPlaceholder("NombreUsuario");
        jPanel9.add(user6);

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 210, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        // TODO add your handling code here:

        this.dispose();
        Log login = new Log();
        login.setVisible(true);
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:

        String Nombre_usuario = user6.getText();
        String Nombre = user2.getText();
        String Apellido = user3.getText();
        String Telefono = user4.getText();
        String Correo = user5.getText();
        String Contraseña = String.valueOf(Password.getPassword());
        String Confirmar_contraseña = String.valueOf(Password2.getPassword());
        txtfuera.setName("txtfuera");
        user6.setName("Usuario");
        user2.setName("Nombre");
        user3.setName("Apellido");
        user4.setName("Telefono");
        user5.setName("Correo");
        Password.setName("Contraseña");
        Password2.setName("Confirmar contraseña");

        javax.swing.JTextField[] Detectar_null = {user6, user2, user3, user4, user5, Password, Password2, txtfuera};
        List<String> Det = new ArrayList<>();

        for (javax.swing.JTextField inf : Detectar_null) {
            if (inf.getText().isEmpty() && !"txtfuera".equals(inf.getName())   ) {
                Det.add(inf.getName());
            }
        }

        if(!Det.isEmpty()) {

            JOptionPane.showMessageDialog(null, "Los siguientes campos: " + Det + " estan nulos", "Aviso!", JOptionPane.ERROR_MESSAGE);

        }else {

            if (Password.getText().equals(Password2.getText())) {

                Usuario usuarioo = new Usuario();
                usuarioo.setNombre_usuario(Nombre_usuario);
                usuarioo.setNombre(Nombre);
                usuarioo.setApellido(Apellido);
                usuarioo.setTelefono(Telefono);
                usuarioo.setCorreo(Correo);
                usuarioo.setContraseña(Contraseña);
                usuarioo.setConfirmar_contraseña(Confirmar_contraseña);

                gesUsuario gesUser = new gesUsuario();
                gesUsuario.setUsuario(usuarioo);

                JOptionPane.showMessageDialog(rootPane, "Cuenta registrada!");

                this.dispose();
                Log login = new Log();
                login.setVisible(true);

            } else {
                JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden", "Aviso!", JOptionPane.ERROR_MESSAGE);

            }

        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void user2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private LIB.JTexfieldPH_Password Password;
    private LIB.JTexfieldPH_Password Password2;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private LIB.JTexfieldPH_FielTex txtfuera;
    private LIB.JTexfieldPH_FielTex user2;
    private LIB.JTexfieldPH_FielTex user3;
    private LIB.JTexfieldPH_FielTex user4;
    private LIB.JTexfieldPH_FielTex user5;
    private LIB.JTexfieldPH_FielTex user6;
    // End of variables declaration//GEN-END:variables
}
